### ISSUE TITLE
Chapter Six, Challenge 4 produces incorrect result

### ISSUE THREAD

**Issue by ILeftTheLaw** [calthoff/tstp#2]
The provided answer to this challenge:

`lst = "Where now? Who now? When now?".split("?")`
`print(lst)`

Produces the following in the shell window:

`['Where now', ' Who now', ' When now', '']`

First question: Where did the question mark go when the original string was split?  In the book's example, you split a string at a period, and the period remained in the output.

Second question: Why is there a double quote mark at the end of the output?

**Comment by cogginproductions** [comment]
I didn't even notice that before when I ran the program, so I went back and tried it again and you are right @ILeftTheLaw. I am also confused by this.

I messed around with different things and can't get the output shown in the solution. I would also like to know what happened?

**Comment by heyjammo** [comment]
I had to put together a few things learned in the chapter to get the clean output including question marks. I split the word list by space giving me a list of six words, and then used join and slicing to assemble a new list of 3 words.

```
words = "Where now? Who now? When now?"
word_list = words.split(" ")
print([ " ".join(word_list[0:2]),
        " ".join(word_list[2:4]),
        " ".join(word_list[4:6]) ]
)
```

**Comment by ILeftTheLaw** [comment]
Very creative way to solve the problem, @heyjammo .  Wish I'd come up with it! :)

**Comment by heyjammo** [comment]
I hope it helps! I just saw your second question above. Maybe this example will help a bit. The .split() method is going to split a string into fields wherever it resides in the string and will eliminate the delimiting character. If that character is at the end of the string (like the '?' in your post), there will be an empty field at the end of the list.

```
csv = "cat,dog,horse,pig,cow"
csv.split(",")
```
output:
```
['cat', 'dog', 'horse', 'pig', 'cow']
```

vs.

```
csv = "cat,dog,horse,pig,cow,"
csv.split(",")
```
output:
```
['cat', 'dog', 'horse', 'pig', 'cow', '']
```

**Comment by calthoff** [comment]
@heyjammo @cogginproductions Hey everyone! This is the old GitHub repo, which means you have an outdated version of the book. You can update by turning on Kindle Automatic Updates: https://www.amazon.com/gp/help/customer/display.html?nodeId=201252670. If you have any questions, feel free to email me at cory[at]theselftaughtprogrammer.io.

**Comment by heyjammo** [comment]
Hi Cory, I have version 1.9 of the book. The tinyurl link on the split() example in the book takes you to the new repo, but the _solutions_ link at the end of the ch06 exercises takes you to this project. I think that's how OP ended up here instead.

**Comment by ILeftTheLaw** [comment]
Kindle Automatic Updates has always been switched to the ON position for me, (I checked today as you requested in your PM, @calthoff ) but as @heyjammo said, the tinyurl link took me here and still does.

**Comment by calthoff** [comment]
@heyjammo @heyjammo Ahh! You are right. Thanks so much for pointing this out. I will fix it and update the book. Thanks again.
